### ISSUE TITLE
Filter container list

### ISSUE THREAD

**Issue by nathanaherne** [tredly/tredly-build#17]
When running a Tredly host with many containers, if can be difficult to find the specific container when using the `list` containers command. Currently the only way to do this is with `... | grep name`, however this is cumbersome.

It would be desirable to allow search for containers by name.

**Comment by pointybeard** [comment]
A suggestion might be something like `tredly search containers <searchString>`

**Comment by laurieodgers** [comment]
This ticket has moved to the Tredly 1.0 repo at tredly/tredly#22
