### ISSUE TITLE
Implement RAM, CPU and Public IPs for Partitions

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly-build#3]
RAM, CPU and Public IPs have not been implemented for partitions. This is being worked on and should see a release very soon.

**Comment by cmanns** [comment]
Public IP's as in additional IP's besides the tredly host primary IP?

+1 if so

**Comment by laurieodgers** [comment]
Yes that is correct. You will be able to assign a pool of public IP addresses to a partition and then assign them to containers within that partition.

You can currently do this manually (partition agnostic) by specifying --ip4_addr="bridge0|(your public ip)/cidr" on the command line when creating a container.

Note that containers can be either private or public, but not both.

**Comment by laurieodgers** [comment]
To clarify - the public IPs will sit on the host, and be proxied to the container(s). This allows more thorough usage of ports/ip addresses. Currently with the above command, the IP sits directly in the container.

**Comment by nathanaherne** [comment]
Partitions do not have to have a external IP, they can use the default external IP.

The way I see it is - the external IPs will be attached to the external interface. Traffic on that IP is proxied to only the containers inside the partition, outgoing traffic from a partition is NATTED out the external IP allocated to it.

**Comment by pointybeard** [comment]
I think this also relates to #35. If that is a duplicate, please let me know.

**Comment by laurieodgers** [comment]
Default partition will always have host's public ip address

**Comment by laurieodgers** [comment]
In preparation of the v1.0 release, I am closing this ticket. A new ticket has been created at the 1.0 repo: tredly/tredly#15 please use this for all future comments.
