### ISSUE TITLE
Build container from a remote path

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly-build#33]
Currently a Tredly container can only be built using a local Tredlyfile.

Add the ability to specify a remote path (e.g. a URL) to pull a Tredlyfile, and it's supporting files, from.

**Comment by laurieodgers** [comment]
Specify --location=http://www.example.com/tredly/mytredlycontainer.txz on the command line.

Change all refs from --path= to --location= as per below.

**Comment by nathanaherne** [comment]
Can we change it to --location= as that is a better description?

**Comment by laurieodgers** [comment]
This has been implemented in tredly v1.0-rc1
