### ISSUE TITLE
Implement partition level persistent storage

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly-build#34]
Partitions should have their own block of persistent storage that containers can utilise. Storage should only be available to containers running in the same partition.

**Comment by dinapappor** [comment]
Hi!

I was just wondering if this was already working. I can see the persistent dataset being created

`zroot/tredly/persistent                 192K  3.20G   192K  /tredly/persistent`

~~But I don't find any mention of it in code or~~ current tredly file. :/

**Comment by dinapappor** [comment]
For anyone else looking for this It's

`persistentStorageUUID=youchoosethename`
Tredly will create this dataset for you.

`persistentMountPoint=/where/you/want/it/inside/the/container`

**Comment by nathanaherne** [comment]
Persistent storage has a few race condition issues that seem unsolvable. The feature used to be in Tredly but we removed it (thats why its not documented) because of these issues. Persistent storage is so useful that it will be implemented again soon.

**Comment by laurieodgers** [comment]
This has been implemented in tredly v1.0-rc1
