### ISSUE TITLE
Allocate external IP addresses to entire partitions, not individual containers.

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly-build#35]
As the title suggests, currently it is possible to request an external IP address at the container level. Instead, external IP addresses should be allocated to an entire partition, NOT to individual containers within a partition. 

Traffic coming in on that IP can only go to that partition. All traffic going out from that partition must be from that external IP address.

**Comment by pointybeard** [comment]
Fairly certain this is a duplicate of https://github.com/tredly/tredly-host/issues/14, but as it relates more to Tredly-build rather than Tredly-host, I am going to leave it open for now.

**Comment by laurieodgers** [comment]
this ticket, #3 and tredly/tredly-host#14 all relate to the same issue

**Comment by pointybeard** [comment]
Yup. Closing this as duplicate.
