### ISSUE TITLE
Hardcoded network settings?

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly-build#38]
Hi, upon installing tredly on a aws instance where we have the vpc network 10.0.0.0/16 I needed to change the network settings when building tredly-host.

I changed to 192.168.100.0/24 when installing (option 5) tredly-host.

However, in the end of the installation I get an error message:

`Setting Host Network
✖ Error: tredly-host: IP 10.0.100.181 falls within your container subnet. If you wish to use this ip address, please change your container subnet
✖ Error: Failed`

As I had already changed this during the initial dialogue I am guessing you have soime hardcoded stuff in the script(s).

I am also seeing that tredly-host.conf and ipfw.rules doesn't get populated with the selected settings.

In cases where I am not using 10/16 as subnet (for instance in my homenetwork where I am running 172.16.0.0/24) this works as expected.

**Comment by laurieodgers** [comment]
Hi dinapappor
Thanks for the bug report & descriptive explanation - I was able to replicate right away.

Fixes are ready to go in the PR, just awaiting @pointybeard to merge these in
