### ISSUE TITLE
Cannot enter hostnames with punctutations during install

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly-build#39]
During install (choosing option 4) to change hostname I get

`Invalid Hostname. Please try again`

For instance I am trying `tredly01.prd.nv.us.domain.internalzone`

**Comment by laurieodgers** [comment]
hi dinapappor 
Thanks for the bug report - I've implemented better hostname checking as per RFC 1123. Fixes are in the PR, just awaiting a merge (wont be far off)
