### ISSUE TITLE
Extra character get's added when using custom nameservers.

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly-build#41]
Hi, if I use customDNS option to add my own nameservers the nameservers get's an extra character at the end.

What I expect:
`nameserver ns.domain.tld`

What I get:
`nameserver ns.domain.tld;`

Thank you for an otherwise great product. :)

**Comment by nathanaherne** [comment]
I am not sure what the issue is but I can say that we have always used IP addresses for DNS so probably haven't had an opportunity to find this bug yet.

**Comment by laurieodgers** [comment]
Interesting that hostnames cause an error but ip addresses don't. I'll fix this up and release a hotfix shortly.
