### ISSUE TITLE
Allow immediate destruction of container.

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly-build#45]
Hi, this is a feature request.

For instance, alot of or infrastructure runs on erlang and elixir. We use hot code reloading to do upgrades etc. One thing that would be insanely neat would be to be able to build releases for erlang or erlang derived languages. For one of the way I've thought about it would be to specify TredlyFile, let's call it `TredlyBuildFile`. I could for instance do: `tredly push container builds --path=/tredly/ptn/prod/tmp/elixir-project --tredlyFile=TredlyBuildFile` (it would default to the regular `Tredlyfile` if not specified).  

In this special TredlyFile I would be able to use the `onStart` variables to instruct tredly to pull down sources and relevant files and packages and do the release, I would then instruct it to upload the release to let's say S3 or whatever storage is appropriate. For this to work I would need to have something like `immediateDestruction=booleanvalue` or something like it, which I would specify in the end of the TredlyFile this could default to a boolean `false` if not specified.  Why do I need it? Well, after building a release it does not make sense to keep the container around since it wouldn't be used after the release is built.

I will probably submit a PR for this (I guess it would be in node.js and bash?). I just wanted to run it by you guys to see what you think about or if it would ever get merged. And also, this feature might already secretly exist.

~~Another usecase for this which is actually related to the above usecase would be to specify a `Tredlydeploy` file.~~

~~I would for instance run it much like the above example. But using a variable of sorts, maybe `inRunningContainer=booleanvalue` which could also default to a boolean `false`. I could then using the rest of the already existing variables/commands in the TredlyFile to download a newer release and then to hot code reloading. Again, let me know if there is a way to accomplish this already.~~
I just realised I can open up a ssh port to the container and have ansible do the actual hot code reload of the new release.

Let me know what you think.

**Comment by nathanaherne** [comment]
I am not sure I am 100% following you but since you can run pretty much any command in your Tredlyfile, you should in theory be able to do this. If I am correct (not sure I am ) we would just need `Destroy` command to the TredlyFile onStart section?

**Comment by dinapappor** [comment]
> I am not sure I am 100% following you but since you can run pretty much any command in your Tredlyfile, you should in theory be able to do this.

Yes, I can create the build-enviroment, that is installing Elixir, Erlang and git. I do not want these installed in the production enviroment. Therefor it makes sense for meto create a build container, build the release, upload it somewhere and then destroy it. 

Since I want **another** container for the production enviroment, like collectd, etc. I do not want erlang and elixir (the releases are self contained) installed in the production. Hence I would like to be able to do it like this. I do not want the same file to both build **and** deploy the erlang projects. This is because I want a clean enviroment inside the containers, and also to be able to hot code reload the erlang projects.

**Comment by nathanaherne** [comment]
Ah, so you want to create containers within containers?

**Comment by dinapappor** [comment]
> Ah, so you want to create containers within containers?

No, I would like to have different Tredlyfiles inside my projects. One that purely creates a container, installs a package, builds a release and then destroys the container after the release build is done. This release will be stored in S3 for my usecase.

I would then like to have another Tredlyfile that I use for deploys.

**Comment by dinapappor** [comment]
This is kind of what I would like to do:

https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin

I want to build releases and have them deployed in an automated fashion.

**Comment by nathanaherne** [comment]
Thanks for clarifying what you are after. We will talk about this when everyone is back at work tomorrow and come back to you asap.

**Comment by dinapappor** [comment]
> Thanks for clarifying what you are after. We will talk about this when everyone is back at work tomorrow and come back to you asap.

Alright! Nice! I could probably implement most of it myself. Any pointers on where stuff happends in the tredly bash code would be nice though. :)

**Comment by dinapappor** [comment]
> If I am correct (not sure I am ) we would just need Destroy command to the TredlyFile onStart section?

@nathanaherne I revised my initial comment in this issue.

Yes, the only thing really (right now) would be to have a destroy option.

**Comment by pointybeard** [comment]
@dinapappor Your ticket has made for a really productive conversation here at Tredly HQ. Based on your last comment, our solution will be to add a flag in the Tredlyfile to trigger destruction once the container has finished building. Something like `destroyAfterCreation=true` under the build options area (the final form might change a little but you get the idea).

It relates heavily to issue https://github.com/tredly/tredly-host/issues/13 and we've added this to our short term feature roadmap. It should make it into a release very soon.

**Comment by nathanaherne** [comment]
We have added a "Development" Tredlyfile to the Tredly Docs which contains the destroyAfterCreate option - http://www.tredly.com/docs/?p=106

**Comment by dinapappor** [comment]
Wow, quick work guys! This will make my sysadmining/devops-life easier in so many ways. Thanks!

**Comment by laurieodgers** [comment]
I am closing this in favour of a ticket on the 1.0 tredly repo, please use this new ticket for all future comments: tredly/tredly#24
