### ISSUE TITLE
Base container off of already built container 

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly-build#46]
Maybe this needs a registry, much like docker, could be in the new Command center?

Some of the operations when building containers sometimes takes alot of time. (Installing alot of packages, running pip install -r requirements.txt, followed by npm etc. Minimizing js, css etc.) This is sometimes a problem, developers complaining on stuff taking alot of time to deploy to staging or production etc. One way of greatly speeding this up would be to base it of an already built container. 

There are a two main ways of accomplishing this as I see it. 
- Specify a base uuid in the TredlyFile - This could be downloaded from the tredly command center if not already on the host.
- If deploying to the same tredly-host, clone the current container to a new container and run update commands there. This would probably need a variable, maybe `cloneCurrent=boolean value`.

If you do not have the manpower or if you lowly prioritize this please let me know in which subprojects of tredly and perhaps even files I would have to look into to write this functionality. I would gladly submit a PR for this.

**Comment by pointybeard** [comment]
Thanks for the suggestion. As it happens, the ability to move and clone existing containers is something we are working on solving already and has been earmarked for our 1.0 release, which is not far off.

**Comment by laurieodgers** [comment]
I am closing this ticket in favour of a new ticket on the tredly repo. Please use this for all future comments tredly/tredly#25
